name: Run Kobo to Airtable Sync

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          cd kobo-airtable-sync
          pip install -r kobo-airtable-sync/requirements.txt

      - name: Run Kobo-Airtable Sync
        run: |
          cd kobo-airtable-sync
          python kobo-airtable-sync/src/kobo_airtable_sync.py
