name: Trigger Kobo-Airtable Sync

on:
  schedule:
    - cron: "*/10 * * * *"   # Runs every 10 minutes
  workflow_dispatch:          # Allows manual execution as well

jobs:
  trigger-subworkflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run the workflow from subdirectory
        run: |
          cd kobo-airtable-sync
          gh workflow run kobo_to_airtable.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
